title = "This Blog Has No Title (yet)"
author = "xiaq"
indexPosts = 5
feedPosts = 10
rootURL = "http://xiaq.me"

[l10n]

[[categories]]
name = "latin"
title = "拉丁语"

[[categories]]
name = "pseudotech"
title = "伪技术"

[[categories]]
name = "misc"
title = "杂记"

[[categories]]
name = "about"
title = "关于"

[[categories]]
name = "-"
title = "所有文章"
