title = "This Blog Has No Title (yet)"
indexPosts = 5
feedPosts = 10
rootURL = "http://xiaq.me"

[l10n]
recentTitle = "最近的文章："
categoryListTitle = "所有类别："

[[categories]]
name = "latin"
title = "拉丁语"

[[categories]]
name = "about"
title = "关于"
